functions/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = 'functions'

urlpatterns = [
    path('', views.index, name='index'),
    path('reward/', views.reward, name='reward'),
    path('configure/', views.configure, name='configure'),
    path('binds/', views.binds, name='binds'),
    path('vars/', views.vars, name='vars'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

functions/templates/functions/command_setter.html
<div id="command-function-form-section">
    <form method="POST" id="command-function-form"> {% csrf_token %}
        <div class="flex row">
            <div class="flex col" style="min-width: 500px;">
                <div id="func-for-command-dd" class="dropdown-container">
                    <div class="label">
                        Function:
                    </div>
                    <div class="placeholder">
                        Select
                    </div>
                    <ul class="dropdown">
                        {% for func_code, func_code_title in func_code_lookup.items %}
                            {% if func_code not in binds.commands %}
                                <div class="dropdown-li-container"><li id="command-bind-create-{{ func_code }}">
                                    {{ func_code_title }}
                                </li></div>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                <div class="flex row">
                    <div class="input-container">
                        <input type="text" id="command-name" placeholder=" " required>
                        <div class="placeholder">
                            Name (excluding "!")
                        </div>
                    </div>
                    <div class="flex col nogap">
                        <div class="flex row center">
                            <label for="command-cooldown-switch" class="center-text">Cooldown & Limits</label>
                            <label class="switch-container" style="transform: scale(0.70);">
                                <input type="checkbox" role="switch" id="command-cooldown-switch">
                                <span class="switch"></span>
                            </label>
                        </div>
                        <small>If enabled, allows you to set various cooldown rules.</small>
                    </div>
                </div>
                <div class="flex col" id="command-cooldown-section" style="display: none;">
                    <div class="flex row">
                        <div class="input-container stretch">
                            <input type="text" id="command-global-cooldown" placeholder=" ">
                            <div class="placeholder">
                                Global cooldown (seconds)
                            </div>
                        </div>
                        <div class="input-container stretch">
                            <input type="text" id="command-user-cooldown" placeholder=" ">
                            <div class="placeholder">
                                User cooldown (seconds)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="vertical-divider"></div>
            <div class="flex col">
                <div class="subheader center-text">
                    Click to Confirm & Bind
                </div>
                <button class="btn" style="--color: green;" id="command-candidate-button" type="submit" disabled>
                    <span class="btn-left">
                        <span class="flex-img-cnt">
                            <i class="bi-braces" style="font-size: 32px;"></i>
                            <span style="text-align: left;">
                                &nbsp;
                                <span id="command-name-candidate">!</span>
                                <br>
                                &nbsp;
                                <small id="command-function-candidate"><i class='bi-gear'></i>&nbsp;</small>
                            </span>
                        </span>
                    </span>
                </button>
            </div>
        </div>
    </form>
</div>

<script>

(function() {

    var funcForCommandDD = new Dropdown($("#func-for-command-dd"), chooseFunctionHandler);
    
    // Form vars
    var authenticationChecks = [];

    $("#command-name").on("keyup", commandCandidateUpdate);
    $("#command-cooldown-switch").on("change", function()
    {
        $("#command-cooldown-section").toggle(this.checked);
        $("#command-global-cooldown").prop("required", this.checked);
        $("#command-user-cooldown").prop("required", this.checked);
    });

    $("#command-function-form").off().on("submit", function(e)
    {
        e.preventDefault();

        $.ajax
        ({
            type: "PUT",
            url: "{% url 'functions:binds' %}",
            headers: {
                Accept: "application/json"
            },
            data: {
                csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
                method: funcMethodDD.getParsedID(),
                function: funcForCommandDD.getParsedID(),
                commandName: $(this).find("#command-name").val(),
                hasCooldown: $(this).find("#command-cooldown-switch").prop("checked"),
                globalCooldown: $(this).find("#command-global-cooldown").val(),
                userCooldown: $(this).find("#command-user-cooldown").val()
            },
            success: loadFunctionUtils,
            error: function(jqXHR, textStatus, errorThrown)
            {
                console.log(jqXHR.responseJSON.msg);
            }
        });
    });

    function chooseFunctionHandler()
    {
        let gearIcon = "<i class='bi-gear'></i>&nbsp;";
        let functionName = "";
        switch (this.getParsedID())
        {
            case "songreq":
                functionName = "Spotify Song Requests";
                authenticationChecks = ["spotify"];
                break;
            case "chatgpt":
                functionName = "ChatGPT Chat Requests";
                authenticationChecks = [];
                break;
            case "songskip":
                functionName = "Spotify Song Skips";
                authenticationChecks = ["spotify"];
                break;
            case "ytreq":
                functionName = "YouTube Requests";
                authenticationChecks = [];
                break;
            case "gptimage":
                functionName = "ChatGPT Image Requests";
                authenticationChecks = [];
                break;
            case "soundreq":
                functionName = "Sound Requests";
                authenticationChecks = [];
                break;
        }

        $("#command-function-candidate").html(gearIcon + functionName);

        modifyCandidateButton();
        modifyAuthButtons();
        return;
    }

    function modifyCandidateButton()
    {
        let allow = true;

        if (authenticationChecks.indexOf("spotify") > -1)
        {
            allow = spotifyAuthed;
        }

        $("#command-candidate-button").prop("disabled", 
            !(
                !!funcForCommandDD.getParsedID() && 
                $("#command-name").val() && 
                allow
            )
        );
    }

    function modifyAuthButtons()
    {
        if (authenticationChecks.indexOf("spotify") > -1)
        {
            spotifyAuthed ? $("#spotifyAuthButton").hide() : $("#spotifyAuthButton").show();
        }
        else
        {
            $("#spotifyAuthButton").hide();
        }
    }

    function commandCandidateUpdate(event)
    {
        $("#command-name-candidate").html("!" + $("#command-name").val());
        modifyCandidateButton();
    }

    /* ===================================================================
     * VALIDATIONS
     * ================================================================ */
    // TODO: Show these validations below input box instead of vanilla browser popup on submit.
    // TODO: Also make it lock submit buttons?
    Validators.forceStrLength($("#command-name"), 1, 30);
    Validators.forceIntInRange($("#command-global-cooldown"), 1);
    Validators.forceIntInRange($("#command-user-cooldown"), 1);
})();

</script>

functions/templates/functions/configurator.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap_icons %}


{% block title %}Function Configuration{% endblock %}
{% block content %}


<div class="info-container">
    <div class="info-header">
        Fine-tune your configurations and slightly change their behaviour to your needs!
    </div>
    <div class="info-body">
        Small tweaks can be made to each of your functions to better suit what you want.<br><br>
        If a behaviour can't be changed here, chances are that somebody else thought of the same thing.<br>
        Feel free to reach out with any suggestions for more customization with your functions!
    </div>
</div>
<div class="page-title">
    Spotify Song Requests
</div>
<form id="vars-songreq-form">
    <div class="flex col">
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Emote</div>
            <div class="center-text ver" style="flex: 3;">
                Upon a successful song request, a message is sent. This is the plain-text emote that appears at the start.
            </div>
            <div class="input-container stretch">
                <input type="text" id="vars-songreq-emote" placeholder=" " value="{{ songreq.emote }}" required>
                <div class="placeholder">
                    Emote
                </div>
            </div>
        </div>
        <button class="btn center-text">Save changes: Spotify Song Requests</button>
    </div>
</form>
<br><hr><br>
<div class="page-title">
    Spotify Song Skips
</div>
<form id="vars-songskip-form">
    <div class="flex col">
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Emote</div>
            <div class="center-text ver" style="flex: 3;">
                Upon a successful song skip, a message is sent. This is the plain-text emote that appears at the start.
            </div>
            <div class="input-container stretch">
                <input type="text" id="vars-songskip-emote" placeholder=" " value="{{ songskip.emote }}" required>
                <div class="placeholder">
                    Emote
                </div>
            </div>
        </div>
        <button class="btn center-text">Save changes: Spotify Song Skips</button>
    </div>
</form>
<br><hr><br>
<div class="page-title">
    ChatGPT Chat Requests
</div>
<form id="vars-chatgpt-form">
    <div class="flex col">
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Clear size</div>
            <div class="center-text ver" style="flex: 3;">
                The number of past exchanges to be cleared at a time until ChatGPT can make more conversation. Due to its limitations,
                ChatGPT can only operate on so much chat information. All messages are stored until the oldest ones need to be cleared out,
                and this number dictates how many exchanges at a time the bot should clear out until ChatGPT can process it.
            </div>
            <div class="input-container stretch">
                <input type="text" id="vars-chatgpt-clearsize" placeholder=" " value="{{ chatgpt.clearsize }}" required>
                <div class="placeholder">
                    Clear size
                </div>
            </div>
        </div>
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Show full</div>
            <div class="center-text ver" style="flex: 3;">
                Determines if smossbot cuts off responses from ChatGPT. If on, smossbot will send as much Twitch messages as it needs to
                post the complete ChatGPT response, typically a maximum of 5. If off, it'll cut it off and replace the end with "... (max 500)".
            </div>
            <div style="flex: 1;">
                <label class="switch-container" style="transform: scale(0.70);">
                    <input type="checkbox" role="switch" id="vars-chatgpt-showfull" {% if chatgpt.showfull %} checked {% endif %}>
                    <span class="switch"></span>
                </label>
            </div>
        </div>
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Max prompt tokens</div>
            <div class="center-text ver" style="flex: 3;">
                Represents how many tokens ChatGPT can use for the chat completion. A shorter number means the responses are forced to be more
                concise, and a larger number means the responses are more thorough. If you set the number lower to make the responses shorter
                though, ChatGPT may give you a garbage/junk response. For reference, OpenAI sets the minimum recommended amount of tokens to 256
                to supply a successful response. 
            </div>
            <div class="input-container stretch">
                <input type="text" id="vars-chatgpt-maxprompttokens" placeholder=" " value="{{ chatgpt.maxprompttokens }}" required>
                <div class="placeholder">
                    Max prompt tokens
                </div>
            </div>
        </div>
        <button class="btn center-text">Save changes: ChatGPT Chat Requests</button>
    </div>
</form>
<br><hr><br>
<div class="page-title">
    YouTube Requests
</div>
<form id="vars-ytreq-form">
    <div class="flex col">
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Max seconds</div>
            <div class="center-text ver" style="flex: 3;">Represents the maximum of seconds that incoming YouTube requests should play for.</div>
            <div class="input-container stretch">
                <input type="text" id="vars-ytreq-maxsecs" placeholder=" " value="{{ ytreq.maxsecs }}" required>
                <div class="placeholder">
                    Max seconds
                </div>
            </div>
        </div>
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Mute Spotify</div>
            <div class="center-text ver" style="flex: 3;">
                Determines if incoming YouTube requests pause your current Spotify playback. The playback remains paused for the duration
                of the YouTube video(s) currently in queue, and resumes only when the YouTube request queue is complete.
            </div>
            <div style="flex: 1;">
                <label class="switch-container" style="transform: scale(0.70);">
                    <input type="checkbox" role="switch" id="vars-ytreq-mutespotify" {% if ytreq.mutespotify %} checked {% endif %}>
                    <span class="switch"></span>
                </label>
            </div>
        </div>
        <button class="btn center-text">Save changes: YouTube Requests</button>
    </div>
</form>
<br><hr><br>

<script>

    /* ===================================================================
     * FORM SUBMISSIONS SETUP
     * ================================================================ */
    // TODO: Is there a better way to do this? Looks like a ton of spaghetti

    // songreq
    $("#vars-songreq-form").on("submit", function(e)
    {
        e.preventDefault();
        
        let data = {
            csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
            function: "songreq",
            emote: $("#vars-songreq-emote").val(),
        };

        $.ajax
        ({
            type: "PATCH",
            url: "{% url 'functions:vars' %}",
            headers: {
                Accept: "application/json"
            },
            data: data,
            success: function() { successful($("#vars-songreq-form").find("button")); },
            error: function() { error($("#vars-songreq-form").find("button")); },
        });
    });

    // songskip
    $("#vars-songskip-form").on("submit", function(e)
    {
        e.preventDefault();
        
        let data = {
            csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
            function: "songskip",
            emote: $("#vars-songskip-emote").val(),
        };

        $.ajax
        ({
            type: "PATCH",
            url: "{% url 'functions:vars' %}",
            headers: {
                Accept: "application/json"
            },
            data: data,
            success: function() { successful($("#vars-songskip-form").find("button")); },
            error: function() { error($("#vars-songskip-form").find("button")); },
        });
    });

    // chatgpt
    $("#vars-chatgpt-form").on("submit", function(e)
    {
        e.preventDefault();
        
        let data = {
            csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
            function: "chatgpt",
            clearsize: $("#vars-chatgpt-clearsize").val(),
            showfull: $("#vars-chatgpt-showfull").prop("checked"),
            maxprompttokens: $("#vars-chatgpt-maxprompttokens").val(),
        };

        $.ajax
        ({
            type: "PATCH",
            url: "{% url 'functions:vars' %}",
            headers: {
                Accept: "application/json"
            },
            data: data,
            success: function() { successful($("#vars-chatgpt-form").find("button")); },
            error: function() { error($("#vars-chatgpt-form").find("button")); },
        });
    });

    // ytreq
    $("#vars-ytreq-form").on("submit", function(e)
    {
        e.preventDefault();
        
        let data = {
            csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
            function: "ytreq",
            maxsecs: $("#vars-ytreq-maxsecs").val(),
            mutespotify: $("#vars-ytreq-mutespotify").prop("checked"),
        };

        $.ajax
        ({
            type: "PATCH",
            url: "{% url 'functions:vars' %}",
            headers: {
                Accept: "application/json"
            },
            data: data,
            success: function() { successful($("#vars-ytreq-form").find("button")); },
            error: function() { error($("#vars-ytreq-form").find("button")); },
        });
    });


    /* ===================================================================
     * BUTTON FEEDBACK FUNCTIONS
     * ================================================================ */
    function successful(btn)
    {
        let original_text = btn.html();

        btn.css("--color", "green");
        btn.prop("disabled", true);
        btn.html("Changes successful!");
        setTimeout(function() { restore(btn, original_text); }, 3000);
    }

    function error(btn)
    {
        let original_text = btn.html();

        btn.css("--color", "red");
        btn.prop("disabled", true);
        btn.html("Changes unsuccessful; check inputs!");
        setTimeout(function() { restore(btn, original_text); }, 3000);
    }

    function restore(btn, original_text)
    {
        btn.css("--color", "");
        btn.prop("disabled", false);
        btn.html(original_text);
    }


    /* ===================================================================
     * VALIDATIONS
     * ================================================================ */
    // TODO: Show these validations below input box instead of vanilla browser popup on submit.
    // TODO: Also make it lock submit buttons?
    Validators.forceStrLength($("#vars-songreq-emote"), 0, 256);
    Validators.forceStrLength($("#vars-songskip-emote"), 0, 256);
    Validators.forceIntInRange($("#vars-chatgpt-clearsize"), 1, 20);
    Validators.forceIntInRange($("#vars-chatgpt-maxprompttokens"), 1);
    Validators.forceIntInRange($("#vars-ytreq-maxsecs"), 1);

</script>


{% endblock %}

functions/templates/functions/index.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap_icons %}


{% block title %}Functions{% endblock %}
{% block content %}


<div class="info-container">
    <div class="info-header">
        Choose which channel point rewards and commands do what on this page!
    </div>
    <div class="info-body">
        Click the <b>Function method</b> dropdown to get started! This controls whether you create either a channel point function
        or a command function.<br>
        Next, click the <b>Function</b> dropdown to choose which functionality you want. If you're looking for Spotify Song Requests, it's in there!<br><br>
        <b>Channel point functions</b>: choose the channel point reward that is tied to it, or let smossbot automatically create one
        for you. This is encouraged so that automatic refunds are possible if redemptions fail!<br>
        <b>Command functions</b>: enter a command name and the rest of the details for that command.<br><br>
        If you want to change the specifics of your already existing function, whether it be which channel point triggers it,
        the command name, or anything else, or delete the function altogether, just click its button at the bottom.
    </div>
</div>
<div class="page-title">
    Create/Set Functions
</div>
<div id="setter">
    <div class="flex col center">
        <div id="func-method-dd" class="dropdown-container">
            <div class="label">
                Function method:
            </div>
            <div class="placeholder">
                Select
            </div>
            <ul class="dropdown">
                {% if is_affiliate %}
                    <div class="dropdown-li-container"><li id="function-method-reward" selected>Channel Points</li></div>
                    <div class="dropdown-li-container"><li id="function-method-command">Commands</li></div>
                {% else %}
                    <div class="dropdown-li-container"><li id="function-method-command" selected>Commands</li></div>
                {% endif %}
            </ul>
        </div>
        <div class="flex col center">
            <div class="center-text" id="func-method-body"></div>
        </div>
        <div class="horizontal-divider"></div>
        <div id="function-form-section"></div>
        <a role="button" class="btn btn-compact center-text" href="{{ spotify_auth_url }}" id="spotifyAuthButton" style="display: none;"><i class="bi-spotify"></i>&nbsp;Sign in with Spotify first!</a>
    </div>
</div>
<br><hr><br>
<div class="page-title">
    Binded Functions
</div>
<div id="viewer">
    Getting binded functions...
</div>


<script>

var funcMethodDD = new Dropdown($("#func-method-dd"), loadFunctionSetter);
var spotifyAuthed = "{{ spotify_authenticated }}" == "True" && "{{ spotify_current }}" == "True";

function loadFunctionSetter()
{
    $.ajax({
        type: "GET",
        url: "{% url 'functions:binds' %}",
        headers: {
            Accept: "text/html"
        },
        data: {
            method: funcMethodDD.getParsedID(),
            template: "setter",
        },
        success: function(data, status, jqXHR)
        {
            $("#function-form-section").html(data);
            toggleMethodHelp();
        }
    });
}

function loadFunctionViewer()
{
    $.ajax({
        type: "GET",
        url: "{% url 'functions:binds' %}",
        headers: {
            Accept: "text/html"
        },
        data: {
            template: "viewer"
        },
        success: function(data, status, jqXHR)
        {
            $("#viewer").html(data);
        }
    });
}

function loadFunctionUtils()
{
    loadFunctionSetter();
    loadFunctionViewer();
}

function toggleMethodHelp()
{
    switch (funcMethodDD.getParsedID())
    {
        case "reward":
            $("#func-method-body").html("Channel Points are currently being used to create and set functions.<br>" +
                "Your functions will trigger off channel point redemptions.<br>" +
                "Choose the function in the Function dropdown, and the channel point reward that triggers it.");
            break;
        case "command":
            $("#func-method-body").html("Commands are currently being used to create and set functions.<br>" +
                "Your functions will trigger off commands.<br>" +
                "Choose the function in the Function dropdown, and fill out the command's details.");
    }
}

loadFunctionUtils();

</script>


{% endblock %}