overlay/urls.py
from django.urls import path

from . import views


app_name = 'overlay'

urlpatterns = [
    path('user/<str:user_hash>/', views.process_req, name='process_req'),
    path('configure/', views.configure, name='configure'),
    path('configurations/', views.configurations, name='configurations')
]

overlay/models.py
from accounts.models import TwitchUser
from django.db import models


class SongReqOverlay(models.Model):
    user = models.OneToOneField(TwitchUser, on_delete=models.CASCADE, primary_key=True)
    enabled = models.BooleanField(default=False)
    constant = models.BooleanField(default=False)
    background = models.BooleanField(default=False)
    vertical_anchor_pos = models.CharField(max_length=12, default="top")
    horizontal_anchor_pos = models.CharField(max_length=12, default="left")


class YTReqOverlay(models.Model):
    user = models.OneToOneField(TwitchUser, on_delete=models.CASCADE, primary_key=True)
    width = models.IntegerField(default=854)
    height = models.IntegerField(default=480)
    vertical_anchor_pos = models.CharField(max_length=12, default="top")
    horizontal_anchor_pos = models.CharField(max_length=12, default="right")

overlay/views.py
import os

from .models import *
from accounts.models import TwitchUser
from django.http import HttpRequest
from django.shortcuts import render
from rest_framework import status
from rest_framework.decorators import api_view, renderer_classes
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response as RESTResponse
from utils import misc, views


def process_req(request, user_hash):
    # TODO-MED: make user_hash an actual hash
    url = None
    if os.getenv('DEBUG') == "True":
        url = "ws://localhost:5000/ws"
    else:
        url = "wss://www.smossbot.com:5000/ws"

    user = TwitchUser.objects.filter(username=user_hash).first()

    ctx = {
        'username': user_hash,
        'url': url,
        'songreqoverlay': user.songreqoverlay,
        'ytreqoverlay': user.ytreqoverlay
    }
        
    return render(request, "overlay/overlay.html", context=ctx)


def configure(request: HttpRequest):
    ctx = views.buildBaseContext(request.user)
    ctx.update({
        'songreqoverlay': request.user.songreqoverlay,
        'ytreqoverlay': request.user.ytreqoverlay,
        'overlay_link': "{}{}{}".format(os.getenv("HOST_URL"), "/overlay/user/", request.user.username)
    })

    return render(request, "overlay/configurator.html", context=ctx)


@api_view(["PATCH"])
@renderer_classes([JSONRenderer])
def configurations(request, format=None):
    overlay_function = request.data.get("overlay_function", None)

    if not overlay_function:
        return RESTResponse(status=status.HTTP_400_BAD_REQUEST)
    
    new_vars = None
    
    if overlay_function == "songreq":
        enabled = request.data.get("enabled", None)
        # constant = request.data.get("constant", None)
        background = request.data.get("background", None)
        vertical_anchor_pos = request.data.get("verticalAnchorPos", None)
        horizontal_anchor_pos = request.data.get("horizontalAnchorPos", None)
        if None in [enabled, background, vertical_anchor_pos, horizontal_anchor_pos]:
            return RESTResponse(status=status.HTTP_400_BAD_REQUEST)
        new_vars = SongReqOverlay(
            user = request.user,
            enabled = misc.strToBool(enabled),
            # constant = misc.strToBool(constant),
            background = misc.strToBool(background),
            vertical_anchor_pos = vertical_anchor_pos.lower(),
            horizontal_anchor_pos = horizontal_anchor_pos.lower(),
        )
    elif overlay_function == "ytreq":
        width = request.data.get("width", None)
        height = request.data.get("height", None)
        vertical_anchor_pos = request.data.get("verticalAnchorPos", None)
        horizontal_anchor_pos = request.data.get("horizontalAnchorPos", None)
        if None in [width, height, vertical_anchor_pos, horizontal_anchor_pos]:
            return RESTResponse(status=status.HTTP_400_BAD_REQUEST)
        new_vars = YTReqOverlay(
            user = request.user,
            width = misc.clampInt(int(width), 0, 2147483647),
            height = misc.clampInt(int(height), 0, 2147483647),
            vertical_anchor_pos = vertical_anchor_pos.lower(),
            horizontal_anchor_pos = horizontal_anchor_pos.lower(),
        )
    else:
        return RESTResponse(status=status.HTTP_400_BAD_REQUEST)
    
    new_vars.save()
    return RESTResponse(status=status.HTTP_200_OK)

overlay/templates/overlay/configurator.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap_icons %}


{% block title %}Configure Overlay{% endblock %}

{% block content %}

<div class="page-title">
    Configure Overlay
</div>

<div class="flex col">
    <div class="center-text">
        <div class="form-text mb-1" id="basic-addon4" style="color: white;">
            This is your Overlay link. Paste this into OBS as a browser source, and make the dimensions<br>
            1920x1080 (width 1920, height 1080).
        </div>
    </div>
    <button type="button" class="btn btn-compact center-text" id="copy-overlay-link-btn">
        Copy Overlay Link&nbsp;&nbsp;<i class="bi-clipboard-fill"></i>
    </button>
    <div class="horizontal-divider"></div>
</div>
<div class="page-title">
    Spotify Song Requests
</div>
<form id="overlay-songreq-form">
    <div class="flex col">
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Enabled</div>
            <div class="center-text ver" style="flex: 3;">This determines if song request overlays are on.</div>
            <div style="flex: 1;">
                <label class="switch-container" style="transform: scale(0.70);">
                    <input type="checkbox" role="switch" id="overlay-songreq-enabled" {% if songreqoverlay.enabled %} checked {% endif %}>
                    <span class="switch"></span>
                </label>
            </div>
        </div>
        <!--div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Constant</div>
            <div class="center-text ver" style="flex: 3;">If song request overlays are on, this determines if the overlay persists even for non-song requests.</div>
            <div style="flex: 1;">
                <label class="switch-container" style="transform: scale(0.70);">
                    <input type="checkbox" role="switch" id="overlay-songreq-constant" {% if songreqoverlay.constant %} checked {% endif %}>
                    <span class="switch"></span>
                </label>
            </div>
        </div-->
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Background</div>
            <div class="center-text ver" style="flex: 3;">If song request overlays are on, this determines if a background is shown to increase readability.</div>
            <div style="flex: 1;">
                <label class="switch-container" style="transform: scale(0.70);">
                    <input type="checkbox" role="switch" id="overlay-songreq-background" {% if songreqoverlay.background %} checked {% endif %}>
                    <span class="switch"></span>
                </label>
            </div>
        </div>
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Vertical Anchor Position</div>
            <div class="center-text ver" style="flex: 3;">If song request overlays are on, this determines where the overlay is positioned vertically.</div>
            <div style="flex: 1;">
                <div id="overlay-songreq-vertical-anchor-pos-dd" class="dropdown-container">
                    <div class="label">
                        Position:
                    </div>
                    <div class="placeholder">
                        Select
                    </div>
                    <ul class="dropdown">
                        <div class="dropdown-li-container"><li>Top</li></div>
                        <div class="dropdown-li-container"><li>Bottom</li></div>
                    </ul>
                </div>
            </div>
        </div>
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Horizontal Anchor Position</div>
            <div class="center-text ver" style="flex: 3;">If song request overlays are on, this determines where the overlay is positioned horizontally.</div>
            <div style="flex: 1;">
                <div id="overlay-songreq-horizontal-anchor-pos-dd" class="dropdown-container">
                    <div class="label">
                        Position:
                    </div>
                    <div class="placeholder">
                        Select
                    </div>
                    <ul class="dropdown">
                        <div class="dropdown-li-container"><li>Left</li></div>
                        <div class="dropdown-li-container"><li>Right</li></div>
                    </ul>
                </div>
            </div>
        </div>
        <button class="btn center-text">Save changes: Spotify Song Requests Overlay</button>
    </div>
</form>
<br><hr><br>
<div class="page-title">
    YouTube Requests
</div>
<form id="overlay-ytreq-form">
    <div class="flex col">
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Width</div>
            <div class="center-text ver" style="flex: 3;">Represents the width of the YouTube player itself.</div>
            <div class="input-container stretch">
                <input type="text" id="overlay-ytreq-width" placeholder=" " value="{{ ytreqoverlay.width }}" required>
                <div class="placeholder">
                    Width
                </div>
            </div>
        </div>
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Height</div>
            <div class="center-text ver" style="flex: 3;">Represents the height of the YouTube player itself.</div>
            <div class="input-container stretch">
                <input type="text" id="overlay-ytreq-height" placeholder=" " value="{{ ytreqoverlay.height }}" required>
                <div class="placeholder">
                    Height
                </div>
            </div>
        </div>
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Vertical Anchor Position</div>
            <div class="center-text ver" style="flex: 3;">This determines where the video is positioned vertically.</div>
            <div style="flex: 1;">
                <div id="overlay-ytreq-vertical-anchor-pos-dd" class="dropdown-container">
                    <div class="label">
                        Position:
                    </div>
                    <div class="placeholder">
                        Select
                    </div>
                    <ul class="dropdown">
                        <div class="dropdown-li-container"><li>Top</li></div>
                        <div class="dropdown-li-container"><li>Bottom</li></div>
                    </ul>
                </div>
            </div>
        </div>
        <div class="flex row center">
            <div class="subheader center-text ver" style="flex: 1;">Horizontal Anchor Position</div>
            <div class="center-text ver" style="flex: 3;">This determines where the video is positioned horizontally.</div>
            <div style="flex: 1;">
                <div id="overlay-ytreq-horizontal-anchor-pos-dd" class="dropdown-container">
                    <div class="label">
                        Position:
                    </div>
                    <div class="placeholder">
                        Select
                    </div>
                    <ul class="dropdown">
                        <div class="dropdown-li-container"><li>Left</li></div>
                        <div class="dropdown-li-container"><li>Right</li></div>
                    </ul>
                </div>
            </div>
        </div>
        <button class="btn center-text">Save changes: YouTube Requests Overlay</button>
    </div>
</form>

<script>

    // TODO: do i even need to say something
    var songreqVerticalAnchorPosDD = new Dropdown($("#overlay-songreq-vertical-anchor-pos-dd"));
    var songreqHorizontalAnchorPosDD = new Dropdown($("#overlay-songreq-horizontal-anchor-pos-dd"));
    var ytreqVerticalAnchorPosDD = new Dropdown($("#overlay-ytreq-vertical-anchor-pos-dd"));
    var ytreqHorizontalAnchorPosDD = new Dropdown($("#overlay-ytreq-horizontal-anchor-pos-dd"));

    songreqVerticalAnchorPosDD.setOption("", capitalize("{{ songreqoverlay.vertical_anchor_pos }}"));
    songreqHorizontalAnchorPosDD.setOption("", capitalize("{{ songreqoverlay.horizontal_anchor_pos }}"));
    ytreqVerticalAnchorPosDD.setOption("", capitalize("{{ ytreqoverlay.vertical_anchor_pos }}"));
    ytreqHorizontalAnchorPosDD.setOption("", capitalize("{{ ytreqoverlay.horizontal_anchor_pos }}"));

    $("#overlay-songreq-form").off().on("submit", function(e)
    {
        e.preventDefault();
        $.ajax
        ({
            type: "PATCH",
            url: "{% url 'overlay:configurations' %}",
            headers: {
                Accept: "application/json"
            },
            data: {
                csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
                overlay_function: "songreq",
                enabled: $("#overlay-songreq-enabled").prop("checked"),
                // constant: $("#overlay-songreq-constant").prop("checked"),
                background: $("#overlay-songreq-background").prop("checked"),
                verticalAnchorPos: songreqVerticalAnchorPosDD.getText(),
                horizontalAnchorPos: songreqHorizontalAnchorPosDD.getText(),
            },
            success: function() { successful($("#overlay-songreq-form").find("button")); },
            error: function() { error($("#overlay-songreq-form").find("button")); }
        });
    });

    $("#overlay-ytreq-form").off().on("submit", function(e)
    {
        e.preventDefault();
        $.ajax
        ({
            type: "PATCH",
            url: "{% url 'overlay:configurations' %}",
            headers: {
                Accept: "application/json"
            },
            data: {
                csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
                overlay_function: "ytreq",
                width: $("#overlay-ytreq-width").val(),
                height: $("#overlay-ytreq-height").val(),
                verticalAnchorPos: ytreqVerticalAnchorPosDD.getText(),
                horizontalAnchorPos: ytreqHorizontalAnchorPosDD.getText(),
            },
            success: function() { successful($("#overlay-ytreq-form").find("button")); },
            error: function() { error($("#overlay-ytreq-form").find("button")); }
        });
    });

    $("#copy-overlay-link-btn").on("click", function()
    {
        navigator.clipboard.writeText("{{ overlay_link }}");

        let btn = $(this);
        let original_text = btn.html();

        btn.css("--color", "green");
        btn.prop("disabled", true);
        btn.html("&nbsp;&nbsp;Copied! Paste into OBS.&nbsp;&nbsp;<i class=\"bi-check-lg\"></i>");

        setTimeout(function() {
            btn.css("--color", "");
            btn.prop("disabled", false);
            btn.html(original_text);
        }, 5000);
    });

    /* ===================================================================
     * BUTTON FEEDBACK FUNCTIONS
     * ================================================================ */
    function successful(btn)
    {
        let original_text = btn.html();

        btn.css("--color", "green");
        btn.prop("disabled", true);
        btn.html("Changes successful!");
        setTimeout(function() { restore(btn, original_text); }, 3000);
    }

    function error(btn)
    {
        let original_text = btn.html();

        btn.css("--color", "red");
        btn.prop("disabled", true);
        btn.html("Changes unsuccessful; check inputs!");
        setTimeout(function() { restore(btn, original_text); }, 3000);
    }

    function restore(btn, original_text)
    {
        btn.css("--color", "");
        btn.prop("disabled", false);
        btn.html(original_text);
    }

    /* ===================================================================
     * VALIDATIONS
     * ================================================================ */
    // TODO: Show these validations below input box instead of vanilla browser popup on submit.
    // TODO: Also make it lock submit buttons?
    Validators.forceIntInRange($("#overlay-ytreq-width"), 0, 2147483647);
    Validators.forceIntInRange($("#overlay-ytreq-height"), 0, 2147483647);

</script>


{% endblock %}

overlay/templates/overlay/overlay.html
{% load static %}


<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <style>
            :root {
                --shadow-width: 10px;
            }

            .songreq-overlay {
                display: none;
                flex: 1;
                flex-direction: column;
                color: #ffffff;
                font-family: Tahoma, sans-serif;
                padding: 15px;
                position: absolute;
            }

            .songreq-overlay.left {
                text-align: left;
                left: var(--shadow-width);
            }

            .songreq-overlay.right {
                text-align: right;
                right: var(--shadow-width);
            }

            .songreq-overlay.top {
                top: var(--shadow-width);
            }

            .songreq-overlay.bottom {
                bottom: var(--shadow-width);
            }

            .songreq-overlay.background {
                border-color: black;
                border-radius: 10px;
                border-style: solid;
                border-width: 2px;

                background: linear-gradient(45deg, #6441a5 0%, #444444 33%, #6441a5 67%, #444444 100%);
                animation: anim 5s linear infinite;
                background-size: 400% 400%;
                background-attachment: fixed;

                box-shadow: 0px 0px var(--shadow-width) 5px black;
            }

            .songreq-overlay > .header {
                font-size: 32px;
            }

            .songreq-overlay > .body {
                font-style: italic;
            }

            @keyframes anim {
                0% {
                    background-position: 100% 0%;
                }
                100% {
                    background-position: 15% 100%;
                }
            }

            .ytreq-overlay {
                position: absolute;
            }

            .ytreq-overlay.left {
                left: 0;
            }

            .ytreq-overlay.right {
                right: 0;
            }

            .ytreq-overlay.top {
                top: 0;
            }

            .ytreq-overlay.bottom {
                bottom: 0;
            }
        </style>
        <link rel="stylesheet" href="{% static 'font/bootstrap-icons.css' %}">
    </head>
    <body>
        {% if songreqoverlay.enabled %}
            <div class="songreq-overlay
                {{ songreqoverlay.vertical_anchor_pos }}
                {{ songreqoverlay.horizontal_anchor_pos }}
                {% if songreqoverlay.background %} background {% endif %}
                " id="songreq-overlay">
                <div class="header" id="songreq-overlay-header">
                    Example Song - Example Artists Here
                </div>
                <div style="margin: 2px 0px;"></div>
                <div class="body" id="songreq-overlay-body">
                    Requested by xzmozxx
                </div>
            </div>
        {% endif %}
        <div class="ytreq-overlay
            {{ ytreqoverlay.vertical_anchor_pos }}
            {{ ytreqoverlay.horizontal_anchor_pos }}
            ">
            <div id="player"></div>
        </div>
    </body>
</html>

<script>
    /* 
     * ==============================================
     * Setup
     * ==============================================
     */

    const username = "{{ username }}";
    const botSocket = new WebSocket("{{ url }}");
    const mediaDir = "{{ MEDIA_URL }}";
    const ytreqOverlay = {
        width: "{{ ytreqoverlay.width }}",
        height: "{{ ytreqoverlay.height }}"
    };
    const fileAPIURL = "{% url 'api:taggedfile' %}";
    var clientID = null;

    botSocket.onopen = (event) =>
    {
        console.log("WebSocket opened!");
        let packet = {
            'username': username, 
            'init': true
        }
        botSocket.send(JSON.stringify(packet));
    }

    botSocket.onmessage = (event) =>
    {
        let incoming_data = JSON.parse(event.data);

        if (!("for" in incoming_data))
            { return; }

        console.log(incoming_data);

        if (incoming_data.for == "ytreq")
        {
            // YT Vid request packet
            let youtube_url = incoming_data.redemption_data.input;
            let youtube_url_blocks = youtube_url.split(/(vi\/|v%3D|v=|\/v\/|youtu\.be\/|\/embed\/)/);
            let youtube_id = undefined !== youtube_url_blocks[2] ? youtube_url_blocks[2].split(/[^0-9a-z_\-]/i)[0] : youtube_url_blocks[0];

            console.log("Received YouTube video request with ID: " + youtube_id);
            addVideoToQueue(youtube_id, incoming_data);
        }
        if (incoming_data.for == "soundreq")
        {
            // Sound request
            console.log("Received sound request: " + incoming_data.redemption_data.input);
            getSound(incoming_data);
        }
        if (incoming_data.for == "songreq")
        {
            // Songreq information packet
            $("#songreq-overlay").toggle(incoming_data.vars.active);
            $("#songreq-overlay-header").text(incoming_data.vars.song_name + " - " + incoming_data.vars.song_artists);
            $("#songreq-overlay-body").text("Requested by " + incoming_data.vars.requester);
            console.log("Received songreq packet.");
        }
    }

    window.onbeforeunload = function()
    {
        botSocket.onclose = function () {}; // disable onclose handler first
        botSocket.close();
        console.log("Closed websocket.");
    }

    $(document).ready(function()
    {
        $.getScript("{% static 'js/youtube.js' %}");
        $.getScript("{% static 'js/soundreq.js' %}");
    });

</script>