dashboard/urls.py
from django.urls import path

from . import views


app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/', views.delete, name='delete'),
]

dashboard/models.py
import os

from accounts.models import TwitchUser
from django.contrib.postgres.fields import ArrayField
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator, FileExtensionValidator
from django.db import models
from django.dispatch import receiver


# CharFields we'll only use whenever we know the length of something, or if something is unlikely to be 50+ chars.
# TextField we'll use for codes, tokens, etc.; things that could be like a million light years long.


# VALIDATORS ==================================================
alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed')

def file_size_checker(value):
    if value.size > 2 * 1024 * 1024:
        raise ValidationError('File size should be max 2MB')
    return

def user_media_path(instance, filename):
    # {{ MEDIA_URL }}/username/filename
    return "{}/{}".format(instance.user.username, filename)

"""
# FILES ===================================================
# Any files that are uploaded by users.
class UploadedFile(models.Model):
    # Use default Django id field, created automatically
    file = models.FileField(validators=[file_size_checker, FileExtensionValidator(allowed_extensions=["mp3", "wav", "ogg"])], upload_to=user_media_path)
    user = models.ForeignKey(TwitchUser, on_delete=models.CASCADE)
    tag = models.CharField(max_length=32, blank=True, null=True, validators=[alphanumeric])
    upload_date = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    purposes = ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True)

@receiver(models.signals.post_delete, sender=UploadedFile)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)
"""

dashboard/forms.py
#from .models import UploadedFile
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.forms import ModelForm, FileInput, TextInput


# VALIDATORS ==================================================
def file_size_checker(value):
    if value.size > 2 * 1024 * 1024:
        raise ValidationError('File size should be max 2MB.')
    return

"""
class UploadForm(ModelForm):
    # file = forms.FileField(validators=[file_size_checker])
    # tag = forms.CharField(validators=[alphanumeric])
    class Meta:
        model = UploadedFile
        fields = ['file', 'tag']
        widgets = {
            'file': FileInput(attrs={
                'class': "form-control compressCenter",
            }),
            'tag': TextInput(attrs={
                'class': "form-control compressCenter",
                'placeholder': "",
                'aria-describedby': "basic-addon3 basic-addon4",
            })
        }
"""

dashboard/views.py
import os

from accounts.models import TwitchUser
from django.contrib.auth import logout
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.cache import never_cache
from functions.models import ChannelPointReward, CommandFunction
from itertools import chain
from utils import views
from utils.users import deleteUser


# ======================================================================================================================
# VIEWS
# ======================================================================================================================
@never_cache
@views.twitchRequired
def index(request: HttpRequest):
    user = request.user

    # If the user isn't in the whitelist for smossbot, give em the L
    if not username_exists(user.username) and user.username != "xzmozxx":
        return HttpResponseRedirect(reverse('gatekept'))
    
    twitch_credentials = user.twitchcredentials
    if not twitch_credentials:
        return HttpResponseRedirect(reverse('home'))

    ctx = views.buildBaseContext(user)
    ctx.update(buildContext(user))

    return render(request, "dashboard/index.html", context=ctx)


@views.twitchRequired
def delete(request: HttpRequest):
    result = deleteUser(request)
    print(result)
    return HttpResponseRedirect(reverse('home'))


# ======================================================================================================================
# NON-VIEW FUNCTIONS
# ======================================================================================================================
def buildContext(user: TwitchUser) -> dict:
    user.refresh_from_db()

    try:
        twitch_authenticated = user.twitchcredentials is not None
    except TwitchUser.DoesNotExist:
        twitch_authenticated = None

    user_reward_binds = ChannelPointReward.objects.filter(user=user)
    user_command_binds = CommandFunction.objects.filter(user=user)

    # TODO-LOW: There's gotta be a better way right?
    songreq_binded = len(user_reward_binds.filter(user=user, binded_to__contains=["songreq"])) + len(user_command_binds.filter(user=user, binded_to__contains=["songreq"])) != 0
    ytreq_binded = len(user_reward_binds.filter(user=user, binded_to__contains=["ytreq"])) + len(user_command_binds.filter(user=user, binded_to__contains=["ytreq"])) != 0
    soundreq_binded = len(user_reward_binds.filter(user=user, binded_to__contains=["soundreq"])) + len(user_command_binds.filter(user=user, binded_to__contains=["soundreq"])) != 0

    ctx = {
        'active_session': user.active_session,
        'twitch_authenticated': twitch_authenticated,
        'songreq_binded': songreq_binded,
        'ytreq_binded': ytreq_binded,
        'soundreq_binded': soundreq_binded
    }

    return ctx


def username_exists(username):
    return TwitchUser.objects.filter(username=username.lower()).exists()

dashboard/templates/dashboard/index.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap_icons %}


{% block title %}Dashboard{% endblock %}

{% block content %}

<div class="page-title">
    Dashboard
</div>

{% if custom_rewards == -1 %}
    <div>
        <b>Sorry {{ twitch_username }}, but you can't set things up at the moment.</b><br><br>
        Right now, functions are only supported via channel point redemptions, and this means you need to <br>
        be at least an affiliate to use smossbot, since affiliates get access to channel point rewards. <br>
        I know, this sucks. But in the future, commands for redemptions may be supported! For now though, keep grinding. &lt;3
    </div>
{% else %}
    <div id="session-controller">
        Loading session controller...
    </div>
    <div class="flex col center">
        <div class="flex center">
            <a role="button" class="btn flex col center-text" href="{% url 'functions:index' %}" style="width: 250px; height: 250px;">
                <i class="bi-link-45deg" style="font-size: 64px;"></i>
                <b>Create/Set Functions</b>
                <small>
                    Give your channel points or commands functions by choosing which ones do what!
                </small>
            </a>
            <a role="button" class="btn flex col center-text" href="{% url 'functions:configure' %}" style="width: 250px; height: 250px;">
                <i class="bi-tools" style="font-size: 64px;"></i>
                <b>Configure Functions</b>
                <small>
                    Fine-tune functions by changing their behaviour to how you'd like.
                </small>
            </a>
            <a role="button" class="btn flex col center-text" href="{% url 'files:index' %}" style="width: 250px; height: 250px;">
                <i class="bi-folder2-open" style="font-size: 64px;"></i>
                <b>File Manager</b>
                <small>
                    Upload files for your functions that smossbot should use!
                </small>
            </a>
            <a role="button" class="btn flex col center-text" href="{% url 'overlay:configure' %}" style="width: 250px; height: 250px;">
                <i class="bi-layers" style="font-size: 64px;"></i>
                <b>Configure Overlay</b>
                <small>
                    Get and configure your overlay link for YouTube Requests, Spotify Song Requests, and more!
                </small>
            </a>
            <button class="btn flex col center-text" id="delete-modal-btn" style="--color: red; width: 250px; height: 250px;">
                <i class="bi-trash3-fill" style="font-size: 64px;"></i>
                <b>Delete All Data</b>
                <small>
                    Delete all information smossbot has stored from you if you no longer wish to be affiliated.
                </small>
            </button>
        </div>
        <a role="button" class="btn btn-compact center-text" href="{{ spotify_auth_url }}" id="spotifyAuthButton" style="display: none;"><i class="bi-spotify"></i>&nbsp;Spotify reauthentication needed!</a>
    </div>
    <div class="horizontal-divider"></div>
    <div class="flex col center">
        {% if songreq_binded %}
            <div class="center-text">
                <b>NOTE:</b> You have the <b>Spotify Song Requests</b> function binded. If you have access to smossbot's internal Spotify queue
                system, head over to the <b>Configure Overlay</b> section to grab your overlay link to show viewers what requested
                song is playing, and who requested it.
            </div>
        {% endif %}
        {% if ytreq_binded %}
            <div class="center-text">
                <b>NOTE:</b> You have the <b>YouTube Requests</b> function binded. Head over to the <b>Configure Overlay</b> section to grab your
                overlay link to actually show the videos on your stream!
            </div>
        {% endif %}
        {% if soundreq_binded %}
            <div class="center-text">
                <b>NOTE:</b> You have the <b>Sound Requests</b> function binded. Head over to the <b>File Manager</b> section to upload your sounds
                that you want, and assign tags to them. Then, head over to the <b>Configure Overlay</b> section to grab your overlay link to
                have the sounds play on your stream!
            </div>
        {% endif %}
    </div>
{% endif %}

<!-- Delete modal -->
<div class="flex center">
    <div class="modal-cnt" id="delete-modal" style="width: 750px;">
        <div class="modal">
            <div class="modal-content">
                <div class="modal-header">
                    Delete All Information
                </div>
                <div class="modal-body">
                    <b>ARE YOU SURE YOU WANT TO DELETE ALL OF YOUR INFORMATION?</b><br><br>
                    <b>ALL</b> information will be lost, including your functions, credentials, authentications, set variables, information in the database,
                    and everything else! It will be as if you never logged on to the website!<br><br>
                    <b>ARE YOU SURE?</b>
                </div>
                <div class="flex row modal-footer">
                    <div class="left">
                        <button class="btn btn-compact" id="delete-modal-btn-close" style="--color: var(--dark-accent-2nd);" type="button">
                            Close
                        </button>
                    </div>
                    <div class="right flex row">
                        <a class="btn btn-compact" href="{% url 'dashboard:delete' %}" id="delete-modal-btn-confirm" style="--color: red;" role="button">
                            <b>Yes I'm sure; NUKE IT.</b>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>

    var deleteModal = new Modal($("#delete-modal"), $("#delete-modal-btn"), $("#delete-modal-btn-close"));
    var spotifyAuthed = "{{ spotify_authenticated }}" == "True" && "{{ spotify_current }}" == "True";

    function loadSessionController()
    {
        $.ajax({
            type: "GET",
            url: "{% url 'api:session' %}",
            headers: {
                Accept: "text/html"
            },
            success: function(data, status, jqXHR)
            {
                $("#session-controller").html(data);
            },
            complete: function()
            {
                let _switch = $("#session-switch");
                _switch.prop("disabled", true);
                setTimeout(function() { _switch.prop("disabled", false); }, 1500);
                _switch.off().on("change", toggleSession);
            }
        });
    }

    function toggleSession()
    {
        let _switch = $("#session-switch");
        let _switch_checked = _switch.prop("checked");
        _switch.disabled = true;

        $.ajax
        ({
            type: "POST",
            url: "{% url 'api:session' %}",
            headers: {
                Accept: "application/json"
            },
            data: {
                csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
                session: _switch.prop("checked"),
            },
            success: loadSessionController,
            error: function() { _switch.disabled = false; _switch.prop("checked", !_switch_checked); },
        });
    }

    loadSessionController();

    if (!spotifyAuthed)
    {
        $("#spotifyAuthButton").show();
    }

</script>


{% endblock %}

dashboard/templates/dashboard/session_controller.html
<div class="info-container">
    {% if not active_session %}
        <label class="switch-container">
            <input type="checkbox" role="switch" id="session-switch">
            <span class="switch"></span>
        </label>
        <div class="info-header">
            smossbot is currently <b>OFF.</b>
        </div>
        <div class="info-body">
            Slide this on to turn the bot on in your chat. You must do this for it to listen for requests and work.
        </div>
    {% else %}
        <label class="switch-container">
            <input type="checkbox" role="switch" id="session-switch" checked>
            <span class="switch"></span>
        </label>
        <div class="info-header">
            smossbot is currently <b>ON.</b>
        </div>
        <div class="info-body">
            smossbot should be in your chat! Type "!ping" in your chat and smossbot should say "Pong!"
            If not, try sliding this off then on again. Sorry for the inconvenience!
            <br><br>
            Make sure to slide this back off when you end stream! This turns the bot off in your chat so you don't get offline requests.<br>
            <b>NOTE:</b> You can get offline requests only for rewards without a cooldown. If your rewards have cooldowns, don't worry.
        </div>
    {% endif %}
</div>