api/urls.py
from django.urls import path

from . import views


app_name = 'api'

urlpatterns = [
    path('session/', views.session, name='session'),
    path('taggedfile/', views.taggedfile, name='taggedfile'),
]

changelog/urls.py
from django.urls import path

from . import views

app_name = 'changelog'

urlpatterns = [
    path('', views.index, name='index'),
]

dashboard/urls.py
from django.urls import path

from . import views


app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/', views.delete, name='delete'),
]

smossbot_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('callback/', include('callback.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('file-manager/', include('files.urls')),
    path('functions/', include('functions.urls')),
    path('overlay/', include('overlay.urls')),
    path('api/', include('api.urls')),
    path('changelog/', include('changelog.urls')),
    path('commands/', views.commands, name='commands'),
    path('about/', views.about, name='about'),
    path('gatekept/', views.gatekept, name='gatekept'),
    path('logout/', views.logout, name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap_icons %}


{% block title %}About & Donate{% endblock %}

{% block content %}
    <div class="page-title">
        About & Donate
    </div>

    <h2>
        <p>
            smossbot is a Twitch bot self-developed by me, Omar (moz).
            <br><br>
            It started as a passion project that was actually intended to run on your local machine as a downloadable program, but
            was later adopted under the vision of providing the functionality from a website, with no downloads required, and virtually
            no resources needing to be used from your PC.
            <br><br>
            The website's frontend and backend, and the Twitch bot that appears in your chat from this website, is all self-developed,
            apart from the frameworks/libraries used of course. The website is built on <a href="https://www.djangoproject.com/">Django</a>, 
            and the Twitch bot itself is built using the <a href="https://twitchio.dev/en/stable/">TwitchIO</a> Python library.
            <br><br>
            This project quickly became one of (and my main) project that I worked on, and I have had a lot of fun learning everything
            and picking up a lot of technologies that were foreign to me. I built smossbot because my friends and I wanted functionalities
            that weren't readily accessible or were really inconvenient to get working; smossbot quickly expanded to provide a bunch of
            other niche little functionalities.
            <br><br>
            I've never made a big project like this, but it's helped me learn more about web development and grow, personally. Because of this
            being a passion project, I always wanted this to be a completely free resource with no crazy paywalls, so that's what it'll remain as.
            If, however, you are feeling very generous and would like to donate, you can do so below.
            <br><br>
            Please only donate if you are financially stable and completely willing to. However, do note that funds raised through this will
            primarily go to me and my family's costs of living, as we aren't in a great spot. Only when I can comfortably receive the funds in good
            conscience will they go towards me. If you are still willing to donate, the button is below. Thank you so much for considering donating
            anything small or big. &lt;3
        </p>
    </h2>

    <div class="flex center">
        <a href="https://www.paypal.com/donate/?business=BJ5MS3TB8LXCS&no_recurring=1&item_name=Thank+you+so+much+for+considering+the+support%3B+if+you%27d+like%2C+you+may+leave+contact+information+so+I+can+thank+you+personally%21&currency_code=USD"
            role="button" class="btn flex col center-text" style="width: 250px; height: 250px;">
            <i class="bi-paypal" style="font-size: 64px;"></i>
            <small>
                Donate via PayPal
            </small>
        </a>
    </div>
  
{% endblock %}

templates/base.html
<!-- templates/base.html -->

{% load static %}
{% load bootstrap_icons %}


<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/validators.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="{% static 'font/bootstrap-icons.css' %}">
        <link rel="icon" href="{% static 'OkayChamp.png' %}" type="image">
        
        <title>smossbot</title>
    </head>
    <body>
        <header> <!-- header tag's got our navbar -->
            <div class="nav-container">
                <nav>
                    <div class="nav-left">
                        <ul class="nav-list">
                            <li class="nav-brand">
                                <a href="{% url 'home' %}" class="nav-link">
                                    <img src="{% static 'smossbotting.gif' %}" alt="Logo" width="50" height="50" class="nav-brand-img">
                                    <b>smossbot</b>
                                </a>
                            </li>
                            {% if twitch_username %}
                                <li class="nav-tab">
                                    <a class="nav-link" href="{% url 'dashboard:index' %}">Dashboard</a>
                                </li>
                            {% endif %}
                            <li class="nav-tab">
                                <a class="nav-link" href="{% url 'commands' %}">Commands</a>
                            </li>
                            <li class="nav-tab">
                                <a class="nav-link" href="{% url 'changelog:index' %}">Changelog</a>
                            </li>
                            <li class="nav-tab">
                                <a class="nav-link" href="{% url 'about' %}">About & Donate</a>
                            </li>
                        </ul>
                    </div>
                    <div class="nav-right">
                        <ul class="nav-list">
                            {% if twitch_username %}
                                <li class="nav-text">
                                    <i class="bi-twitch"></i>&nbsp;<b>{{ twitch_username }}</b>
                                </li>
                                <li class="nav-tab">
                                    <a role="button" class="btn nav-btn" href="{% url 'logout' %}" style="--color: red;" tabindex="0">Log Out&nbsp;<i class="bi-box-arrow-in-right"></i></a>
                                </li>
                                {% if superuser %}
                                    <li class="nav-tab">
                                        <a role="button" class="btn nav-btn" href="{% url 'admin:index' %}" style="--color: blue;" tabindex="0">Admin&nbsp;<i class="bi-person-badge-fill"></i></a>
                                    </li>
                                {% endif %}
                            {% else %}
                                <li class="nav-tab">
                                    <a role="button" class="btn nav-btn" href="{{ twitch_auth_url }}" style="--color: #6441a5;"><i class="bi-twitch"></i>&nbsp;Sign in with Twitch</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </nav>
            </div>
        </header>
        <main>
            <div class="dim-background" id="dimBackground" style="display: none;"></div>
            <div class="main-container">
                {% if messages %}
                    <div class="base-messages">
                        <br>
                        {% for message in messages %}
                            <div class="alert alert-dismissible fade show
                            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} alert-danger
                            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} alert-success {% endif %}
                            " role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="base-content">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </main>
        <footer>
            <div class="footer-section">
                Please keep in mind that this site is still under development. <br>
                If any bugs happen or inquiries arise, please report them to me!
            </div>
            <div class="footer-section">
                <i class="bi-discord"></i>&nbsp;Discord: .moz.<br>
                <i class="bi-envelope"></i>&nbsp;Inquiries: omarg19999@gmail.com<br>
            </div>
            <div class="footer-section">
                <a href="https://github.com/RMXdotEXE/smossbot-web"><i class="bi-github"></i>&nbsp;Website GitHub</a><br>
                <i class="bi-github"></i>&nbsp;Twitch Bot GitHub - TBD
            </div>
        </footer>
    </body>
</html>

<script>

$.ajaxSetup({
    headers: {"X-CSRFToken": "{{ csrf_token }}"}
});


// https://stackoverflow.com/questions/6234773/can-i-escape-html-special-chars-in-javascript
function escapeHTML(unsafe)
{
    return unsafe
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
 }

</script>

templates/commands.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap_icons %}


{% block title %}Commands{% endblock %}

{% block content %}
<div class="page-title">
    smossbot's commands for the plebs
</div>
<div class="flex row center">
    <div class="command-cnt white-shadow" style="flex: 1;">
        <div class="command-name center-text">!help</div>
        <div class="command-body center-text">
            Links you to this page!
        </div>
        <div class="command-footer center-text">Permission level: Viewer</div>
    </div>
    <div class="command-cnt white-shadow" style="flex: 1;">
        <div class="command-name center-text">!ping</div>
        <div class="command-body center-text">
            smossbot responds with <b>&nbsp;Pong!&nbsp;</b> to let you know it's active and listening.
        </div>
        <div class="command-footer center-text">Permission level: Viewer</div>
    </div>
    <div class="command-cnt white-shadow" style="flex: 1;">
        <div class="command-name center-text">!song</div>
        <div class="command-body center-text">
            Gets the song that's currently playing, along with the progress of the song.
        </div>
        <div class="command-footer center-text">Permission level: Viewer</div>
    </div>
</div>
<hr>
<div class="page-title">
    smossbot's commands for the MODS
</div>
<div class="command-cnt white-shadow">
    <div class="command-name center-text">!songreq &lt;action&gt; &lt;query&gt;</div>
    <div class="command-body">
        <br>
        Accesses the Spotify Song Request function, and allows Moderators (by default) to run utilities.
        <br><br>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">action</th>
                    <th scope="col">query</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">add</th>
                    <td>Spotify URI, share link, search query, etc.</td>
                </tr>
                <tr>
                    <th scope="row">queue</th>
                    <td>
                        <div class="flex col center">
                            <div>start - Starts the internal queue with a recurring task. It runs every 5 seconds, updating itself with the current queue for incoming song requests each time.</div>
                            <div>stop - Stops the internal queue, and destroys the recurring task. (pls do this)</div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="command-footer center-text">Permission level: Moderator+ (by default)</div>
</div>

<div class="command-cnt white-shadow">
    <div class="command-name center-text">!songskip</div>
    <div class="command-body center-text">
        Manually skips the song currently playing.
    </div>
    <div class="command-footer center-text">Permission level: Moderator+</div>
</div>

<div class="command-cnt white-shadow">
    <div class="command-name center-text">!variable &lt;variablename&gt; &lt;value&gt;</div>
    <div class="command-body">
        <br>
        Updates various values that tweak how certain parts of smossbot work, so you can fine-tune behaviours.
        <br><br>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">variablename</th>
                    <th scope="col">value</th>
                    <th scope="col">Purpose</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">songreq:emote</th>
                    <td>Any</td>
                    <td>The emote that appears before the song request message.
                        <br><small><i>Default: Okayge</i></small>
                    </td>
                </tr>
                <tr>
                    <th scope="row">chatgpt:clearsize</th>
                    <td>[1,2,3,...]</td>
                    <td>
                        An integer (whole number) representing how many past exchanges should be cleared at a time until ChatGPT can
                        continue on with more conversations.
                        <br><small><i>Default: 2</i></small>
                    </td>
                </tr>
                <tr>
                    <th scope="row">chatgpt:showfull</th>
                    <td>True OR False</td>
                    <td>
                        If set to "true", smossbot will not cut off the response from ChatGPT, which will lead to <b>a lot</b> of
                        messages from smossbot. Precisely, smossbot will send as much Twitch messages as it needs to post the complete
                        ChatGPT response, typically a maximum of 5. If set to "false" (or anything else), it'll cut it off and replace
                        the end with "... (max 500)".
                        <br><small><i>Default: false</i></small>
                    </td>
                </tr>
                <tr>
                    <th scope="row">chatgpt:maxprompttokens</th>
                    <td>[1,2,3,...]</td>
                    <td>
                        An integer (whole number) representing how many tokens ChatGPT can use for the chat completion. A shorter number
                        means the responses are forced to be more concise, and a larger number means the responses are more thorough.
                        If you set the number too short for responses to be shorter though, ChatGPT may give you a garbage/junk response. 
                        For reference, 256 is the minimum recommended amount of tokens ChatGPT needs to supply a successful response.
                        <br><small><i>Default: 256</i></small>
                    </td>
                </tr>
                <tr>
                    <th scope="row">gptimage:imagesize</th>
                    <td>[1,2,3]</td>
                    <td>
                        An integer (whole number) between 1 and 3, inclusive, representing the size of generated images by ChatGPT. The 
                        sizes, respectively, are: 256x256, 512x512, and 1024x1024.
                        <br><small><i>Default: 2</i></small>
                    </td>
                </tr>
                <tr>
                    <th scope="row">songskip:emote</th>
                    <td>Any</td>
                    <td>The emote that appears before the song skip message.
                        <br><small><i>Default: PepeLaugh</i></small>
                    </td>
                </tr>
                <tr>
                    <th scope="row">ytreq:maxsecs</th>
                    <td>[1,2,3,...]</td>
                    <td>An integer (whole number) representing how many seconds, at the maximum, incoming YouTube requests should play for.
                        <br><small><i>Default: 60</i></small>
                    </td>
                </tr>
                <tr>
                    <th scope="row">ytreq:mutespotify</th>
                    <td>"true" OR "false"</td>
                    <td>If set to "true", incoming YouTube requests will pause your Spotify playback for the duration of the videos.
                        If multiple videos are queued, Spotify will only resume once all queued videos are done.
                        <br><small><i>Default: true</i></small>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="command-footer center-text">Permission level: Moderator+ OR xzmozxx</div>
</div>
  
{% endblock %}

templates/gatekept.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap_icons %}


{% block title %}Gatekept{% endblock %}

{% block content %}
<div class="flex col center info-container">
    <div class="info-header">
        Sorry {{ twitch_username }}, I really don't want you here...
    </div>
    <div class="info-body">
        Just kidding; only a select few people have access to smossbot, sorry!
        For now, wait for updates, check back at a later date, or message me to see about getting access.<br><br>
        Had access before? You probably changed your username or something about it, so DM me to get it fixed.<br><br>
        <a class="btn btn-compact center-text" href="{% url 'logout' %}" role="button">
            Log Out&nbsp;&nbsp;<i class="bi-box-arrow-in-right"></i>
        </a>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div>
    <div class="page-title">
        smossbot being publicly released soon!
    </div>

    <h2>
        {% if twitch_username %}
        <div class="flex center">
            <a role="button" class="btn flex col center-text" href="{% url 'dashboard:index' %}" style="width: 250px; height: 250px;">
                <div>Hey {{ twitch_username }}!</div>
                <div><b>Head to your dashboard</b></div>
                <br>
                <div><i class="bi-arrow-right"></i><i class="bi-arrow-right"></i><i class="bi-arrow-right"></i></div>
            </a>
        </div>
            <br><br>
        {% endif %}
    </h2>

    <h2>
        <p>
            smossbot is a Twitch bot that offers features for your stream, right from your chat for your viewers to use.
            <br><br>
            Through this website, you can set up features such as Spotify song requests, ChatGPT conversations, and YouTube video requests - all from this website in a matter of minutes!
            <br><br>
            smossbot is currently in open beta, which means the bot is available to use for anybody. However, the bot is incomplete in this state; features and fixes are incrementally being added.
            <br><br>
            If there are any questions about how to get things set up, feel free to contact me!
        </p>
    </h2>
</div>

{% endblock %}